"""test field

Revision ID: fb36a3b950de
Revises: 811af5c33b69
Create Date: 2024-04-06 15:47:27.688989

"""
import typing

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb36a3b950de'
down_revision: typing.Union[str, None] = '811af5c33b69'
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('test_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'test_field')
    # ### end Alembic commands ###
