"""dell test field

Revision ID: b1fb2bee026d
Revises: fb36a3b950de
Create Date: 2024-04-06 16:14:33.103593

"""
import typing

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fb2bee026d'
down_revision: typing.Union[str, None] = 'fb36a3b950de'
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
