"""init

Revision ID: 811af5c33b69
Revises: 
Create Date: 2024-04-06 14:47:11.970370

"""
import typing

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811af5c33b69'
down_revision: typing.Union[str, None] = None
branch_labels: typing.Union[str, typing.Sequence[str], None] = None
depends_on: typing.Union[str, typing.Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('joke_id', sa.UUID(), nullable=False),
    sa.Column('text_final', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('joke_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###
